# .github/dependabot.yml

version: 2
updates:
  # Enable updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable updates for Python dependencies in pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore updates to boto3 since it's provided by AWS Lambda
      - dependency-name: "boto3"

